### ISSUE TITLE
Ejercicio 11: Formularios y modals

### ISSUE THREAD

**Issue by mariasanguesa** [resanocristina/appGaztaroa_maria_cris#12]

**Comment by resanocristina** [comment]
En este ejercicio, no existe mucha complicación si ya has entendido como funciona Redux en las prácticas anteriores. En definitiva, la primera parte de la práctica te pide introducir una especie de formulario para poder postear reseñas en las diferentes excursiones. En primer lugar, introducir el icono que te lleva al formulario es simple, se trata añadir un nuevo icono cuyo name será pencil, para que muestro ese dibujo dentro del icono. El color en este caso elegido ha sido uno de los que tenemos configurados por tema en nuestra app, que es el azul oscuro. Y al presionar el icono, nos vamos a mostrar el formulario. Renderizar el formulario no ha tenido complejidad, se crea a gusto del integrador a partir de los componentes que te oferce react native. Las estrellas las introducimos con el componente 'Rating' que ofrece la libreria react native ratings. 

Para la segunda parte, debemos asociar los botones del formulario a nuestros estados de redux. Uno de los botones nos permitirá añadir y postear los comentarios y otro dejará el estado de los comentarios como se encontraba hasta el momento. Para ello, deberemos añadir dos actions types nuevas y desarollar su lógica en el action creators.
